import { User } from '@supabase/supabase-js';
import { Antique, Catalog } from '../models';

const ADMIN_ID = '00000000-0000-0000-0000-000000000001';

export const MOCK_ADMIN: User = {
  id: ADMIN_ID,
  aud: 'authenticated',
  email: 'admin@antiguedades.com',
  phone: '',
  app_metadata: { provider: 'email' },
  user_metadata: { full_name: 'Admin' },
  created_at: new Date().toISOString(),
  role: 'authenticated',
  confirmed_at: new Date().toISOString(),
  last_sign_in_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  identities: [],
  factors: [],
};

export const MOCK_CATALOGS: Catalog[] = [
  {
    id: 'cat-1',
    name: 'Relojería Antigua',
    description: 'Relojes de péndulo, bolsillo y sobremesa de los siglos XVIII y XIX',
    cover_image: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=400&h=300&fit=crop',
    created_by: ADMIN_ID,
    created_at: '2024-01-15T10:00:00Z',
    antiques_count: 4,
  },
  {
    id: 'cat-2',
    name: 'Porcelana y Cerámica',
    description: 'Piezas de porcelana fina europea y cerámica artesanal',
    cover_image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400&h=300&fit=crop',
    created_by: ADMIN_ID,
    created_at: '2024-02-20T10:00:00Z',
    antiques_count: 3,
  },
  {
    id: 'cat-3',
    name: 'Mobiliario Clásico',
    description: 'Muebles antiguos restaurados de los siglos XIX y XX',
    cover_image: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=400&h=300&fit=crop',
    created_by: ADMIN_ID,
    created_at: '2024-03-10T10:00:00Z',
    antiques_count: 3,
  },
];

export const MOCK_ANTIQUES: Antique[] = [
  {
    id: 'ant-1',
    catalog_id: 'cat-1',
    name: 'Reloj de Péndulo Victoriano',
    type: 'antiguedad',
    subcategory: 'escultura',
    detail: 'figura',
    country: 'Inglaterra',
    region: '',
    element: '',
    description: 'Impresionante reloj de péndulo de la época victoriana, tallado en roble macizo con detalles en bronce dorado. Mecanismo de cuerda semanal con sonería en campana. Perfecto estado de funcionamiento.',
    price: 3200,
    year_era: 'Victoricano tardío, ca. 1880',
    condition: 'Excelente',
    material: 'Roble, Bronce, Esmalte',
    dimensions: '210 x 50 x 30 cm',
    images: [
      'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567532900872-f4e906cbf06a?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'ant-2',
    catalog_id: 'cat-1',
    name: 'Reloj de Bolsillo Suizo',
    type: 'antiguedad',
    subcategory: 'escultura',
    detail: 'figura',
    country: 'Suiza',
    region: '',
    element: '',
    description: 'Reloj de bolsillo suizo de la marca Omega, fabricado en 1920. Caja de plata de ley 925, esfera esmaltada con números romanos. Incluye cadena original.',
    price: 1800,
    year_era: '1920s',
    condition: 'Bueno',
    material: 'Plata, Esmalte, Acero',
    dimensions: '5 cm de diámetro',
    images: [
      'https://images.unsplash.com/photo-15995808-6f0ed3e44b2a?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-01-25T10:00:00Z',
  },
  {
    id: 'ant-3',
    catalog_id: 'cat-1',
    name: 'Reloj de Sobremesa Art Decó',
    type: 'antiguedad',
    subcategory: 'escultura',
    detail: 'figura',
    country: 'Francia',
    region: '',
    element: '',
    description: 'Elegante reloj de sobremesa del período Art Decó francés. Caja de mármol verde con aplicaciones de bronce patinado. Esfera de esmalte blanco con numerals Art Decó.',
    price: 2400,
    year_era: 'Art Decó, ca. 1930',
    condition: 'Excelente',
    material: 'Mármol, Bronce, Esmalte',
    dimensions: '30 x 15 x 10 cm',
    images: [
      'https://images.unsplash.com/photo-1567532900872-f4e906cbf06a?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'ant-4',
    catalog_id: 'cat-1',
    name: 'Reloj Despertador Mecánico',
    type: 'antiguedad',
    subcategory: 'escultura',
    detail: 'figura',
    country: 'Alemania',
    region: '',
    element: '',
    description: 'Reloj despertador mecánico alemán de los años 1950. Carcasa de baquelita negra, mecanismo de cuerda de 8 días. Funciona perfectamente.',
    price: 450,
    year_era: '1950s',
    condition: 'Regular',
    material: 'Baquelita, Acero, Latón',
    dimensions: '12 x 8 x 6 cm',
    images: [
      'https://images.unsplash.com/photo-15995808-6f0ed3e44b2a?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-02-10T10:00:00Z',
  },
  {
    id: 'ant-5',
    catalog_id: 'cat-2',
    name: 'Jarrón de Porcelana de Limoges',
    type: 'antiguedad',
    subcategory: 'ceramica',
    detail: '',
    country: 'Francia',
    region: '',
    element: '',
    description: 'Espectacular jarrón de porcelana de Limoges pintado a mano con motivos florales. Decoración en oro de 24K. Sello del fabricante en la base.',
    price: 2800,
    year_era: 'Francia, ca. 1890',
    condition: 'Excelente',
    material: 'Porcelana, Oro',
    dimensions: '45 x 25 cm',
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-02-22T10:00:00Z',
  },
  {
    id: 'ant-6',
    catalog_id: 'cat-2',
    name: 'Juego de Té de Porcelana Inglesa',
    type: 'antiguedad',
    subcategory: 'ceramica',
    detail: '',
    country: 'Inglaterra',
    region: '',
    element: '',
    description: 'Juego de té completo de porcelana inglesa Royal Crown Derby. Compuesto por tetera, 6 tazas con platos, lechera y azucarero. Decoración de estilo Imari en azul, rojo y oro.',
    price: 3600,
    year_era: 'Inglaterra, ca. 1900',
    condition: 'Bueno',
    material: 'Porcelana',
    dimensions: 'Tetera: 20 x 15 cm',
    images: [
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-03-05T10:00:00Z',
  },
  {
    id: 'ant-7',
    catalog_id: 'cat-2',
    name: 'Plato Decorativo de Sevres',
    type: 'antiguedad',
    subcategory: 'ceramica',
    detail: '',
    country: 'Francia',
    region: '',
    element: '',
    description: 'Plato decorativo de porcelana de Sevres con escena pastoral pintada a mano. Marco de bronce dorado. Perfecto para coleccionistas de porcelana francesa.',
    price: 1200,
    year_era: 'Francia, ca. 1880',
    condition: 'Para restaurar',
    material: 'Porcelana, Bronce',
    dimensions: '32 cm de diámetro',
    images: [
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-03-12T10:00:00Z',
  },
  {
    id: 'ant-8',
    catalog_id: 'cat-3',
    name: 'Sillón Luis XV',
    type: 'antiguedad',
    subcategory: 'escultura',
    detail: 'figura',
    country: 'Francia',
    region: '',
    element: '',
    description: 'Sillón de la época Luis XV restaurado, con tallas en madera de haya dorada y tapicería de seda natural color crema. Asiento cómodo y brazos elegantemente curvados.',
    price: 4500,
    year_era: 'Francia, ca. 1760',
    condition: 'Excelente',
    material: 'Haya dorada, Seda',
    dimensions: '95 x 70 x 75 cm',
    images: [
      'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'ant-9',
    catalog_id: 'cat-3',
    name: 'Aparador Isabelino',
    type: 'antiguedad',
    subcategory: 'escultura',
    detail: 'figura',
    country: 'España',
    region: '',
    element: '',
    description: 'Aparador de roble macizo de estilo isabelino español. Tres cuerpos con puertas talladas, interior con estantes. Cerraduras y herrajes originales de hierro forjado.',
    price: 3800,
    year_era: 'España, ca. 1900',
    condition: 'Bueno',
    material: 'Roble macizo, Hierro forjado',
    dimensions: '180 x 100 x 50 cm',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-03-20T10:00:00Z',
  },
  {
    id: 'ant-10',
    catalog_id: 'cat-3',
    name: 'Mesa de Centro Modernista',
    type: 'antiguedad',
    subcategory: 'escultura',
    detail: 'figura',
    country: 'España',
    region: 'Cataluña',
    element: '',
    description: 'Mesa de centro de la época modernista catalana, con sobre de mármol negro y base de hierro forjado con motivos florales. Pieza única de gran valor decorativo.',
    price: 2100,
    year_era: 'Modernismo catalán, ca. 1910',
    condition: 'Regular',
    material: 'Mármol negro, Hierro forjado',
    dimensions: '120 x 60 x 75 cm',
    images: [
      'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&h=600&fit=crop',
    ],
    created_by: ADMIN_ID,
    created_at: '2024-04-01T10:00:00Z',
  },
];

let nextAntiqueId = 11;
let nextCatalogId = 4;

function generateId(prefix: string): string {
  return `${prefix}-${nextAntiqueId++}`;
}

export function resetMockIds() {
  nextAntiqueId = 11;
  nextCatalogId = 4;
}

export function getNextAntiqueId(): string {
  return `ant-${nextAntiqueId++}`;
}

export function getNextCatalogId(): string {
  return `cat-${nextCatalogId++}`;
}
